### ISSUE TITLE
Create a release for version 0.0.0.9000

### ISSUE THREAD

**Issue by ryanraaum** [eliocamp/ggnewscale#1]
Could you make a release on GitHub for your first version 0.0.0.9000 of ggnewscale? I'm using it in a project and I like to lock down all the versions of the software using conda and I need a tagged release for your package to be able to do that. Thanks!

**Comment by eliocamp** [comment]
Here you go! 
https://github.com/eliocamp/ggnewscale/releases/tag/v0.1.0

Helped me learn a bit about Zenodo integration to get DOIs for releases :)

**Comment by ryanraaum** [comment]
@eliocamp Great - thanks!
