### ISSUE TITLE
isFALSE and isTRUE don't exist for older R

### ISSUE THREAD

**Issue by raymondben** [eliocamp/ggnewscale#12]
`isFALSE` and `isTRUE` were introduced to base in (I believe) R 3.5. I happen to be using an old R (3.4) so I am getting errors along the lines of:
```
Error in isFALSE(scale$guide) : could not find function "isFALSE"
```
Which is not a major headache, but it took a little while to figure out. I guess you could either specify
```
Depends: R (>= 3.5)
```
in the DESCRIPTION file (though then the package won't be usable by anyone pre 3.5), or define your own `isFALSE` and `isTRUE` functions.

**Comment by eliocamp** [comment]
Thanks!
