### ISSUE TITLE
ggnewscale doesn't work with more than one call to new_scale()

### ISSUE THREAD

**Issue by willgearty** [eliocamp/ggnewscale#14]
I'm not sure if this package was designed to work for multiple calls of new_scale(), but at the moment it doesn't seem to. I feel like this has worked in the past, though, so it seems like it may be a regression due to a recent change.

Example:
```r
library(ggplot2)
library(ggnewscale)
# Equivalent to melt(volcano)
topography <- expand.grid(x = 1:nrow(volcano),
                          y = 1:ncol(volcano))
topography$z <- c(volcano)

set.seed(42)
measurements <- data.frame(x1 = runif(30, 1, 80),
                           x2 = runif(30, 1, 80),
                           y = runif(30, 1, 60),
                           thing = rnorm(30))

ggplot() +
  geom_contour(data = topography, aes(x = x, y = y, z = z, color = stat(level))) +
  scale_color_viridis_c(option = "D") +
  new_scale_color() +
  geom_point(data = measurements, size = 3, aes(x = x1, y = y, color = thing)) +
  scale_color_viridis_c(option = "A") +
  new_scale_color() +
  geom_point(data = measurements, size = 3, aes(x = x2, y = y, color = thing))
```

Results in the error:
```r
Error in eval(parse(text = parent.layer$geom)) : 
  object 'NewGeomContour' not found
```

It works fine if you get rid of the last two lines.

**Comment by eliocamp** [comment]
Ahhh, dammit! :sob: 

It should work with an arbitrary number of  scales. And it did until I fixed #13. I'll reopen that issue and try to fix both of them. 
In the meantime, you can install the previous version with `remotes::install_github("eliocamp/ggnewscale@7d4d3358056f90c3e90a5858e69d575849f40bd2")`.

**Comment by willgearty** [comment]
Oh no!
I'm not sure if it helps, but it appears that the `ggedit::cloneLayer()` function is causing issues in other cases, such as the following:
```r
library(tidyverse)
library(tidybayes)
library(deeptime)

tb <- 
    tibble(time = 0:100) %>%
    group_by_all() %>%
    do(tibble(value = rnorm(100, .$time, 10),
              group = sample(1:4, 100, TRUE)))

gg <- 
    tb %>%
    ggplot() +
    stat_lineribbon(aes(x = time, y = value)) +
    scale_x_reverse() +
    coord_cartesian(xlim = c(0, 100), 
                    ylim = range(tb$value),
                    expand = FALSE) +
    facet_wrap(~ group) +
    scale_fill_brewer()

gggeo_scale_old(gg)
```
In this case, it appears to be caused by the `facet_wrap` (it works fine when that line is removed).

**Comment by eliocamp** [comment]
Mh... that sounds bad. I think I'll revert that change and look for other solutions to #13.
