### ISSUE TITLE
Vertically align two legend groups

### ISSUE THREAD

**Issue by Drosof** [eliocamp/ggnewscale#20]
Hi Elio,
I have two fill legend groups `new_scale()`, is there a simple way to align them vertically on the top of the plot? I can't figure it out.
Thanks

**Comment by eliocamp** [comment]
Hi! That's just "base" ggplot. You need to use `+ theme(legend.position="top")`. See here: http://www.cookbook-r.com/Graphs/Legends_(ggplot2)/

**Comment by Drosof** [comment]
Yes this is to position them on top of the plot which does work but my two legends align horizontally and I'd like them to align vertically.

**Comment by eliocamp** [comment]
Yes, you need to put guide = guide_legend(direction = "horizontal") into the scale_fill_continuous (or whatever scale you use) call.

**Comment by Drosof** [comment]
I use 'guide = guide_legend(direction = "horizontal")' for guides so that both of them are laying horizontally but I can't manage to place them pn top of each other. Sorry I don't have a reproducible example at the moment but I'll post one if I don't figure out the issue.

**Comment by Drosof** [comment]
Hi, sorry to bother agsin but here's an example of my problem:

```
topography <- expand.grid(x = 1:nrow(volcano),
                          y = 1:ncol(volcano))

topography$z <- c(volcano)

measurements <- data.frame(x = runif(30, 1, 80),
                           y = runif(30, 1, 60),
                           thing = rnorm(30))

guide1 <- guide_legend(direction = "horizontal",
                       order = 1)
guide2 <- guide_legend(direction = "horizontal",
                       order = 2)

ggplot(mapping = aes(x, y)) +
  geom_contour(data = topography, aes(z = z, color = stat(level))) +
  scale_color_viridis_c(option = "D", guide = guide1) +
  new_scale_color() +
  geom_point(data = measurements, size = 3, aes(color = thing)) +
  scale_color_viridis_c(option = "A", guide = guide2) +
  theme_bw() +
  theme(legend.position = "top")
```
Basically I would like the legend of `thing` to be placed under the legend of `level` on top of the plot.

Besides I also wonder why the legend items lose their gradient style for lines and points when adding specific `guide_legend()` for each legend group.
Thanks

**Comment by eliocamp** [comment]
Per [this question](https://stackoverflow.com/questions/13143894/how-do-i-position-two-legends-independently-in-ggplot) maybe using `legend.box = "vertical"` does the trick:

``` r
library(ggplot2)
library(ggnewscale)

topography <- expand.grid(x = 1:nrow(volcano),
                          y = 1:ncol(volcano))

topography$z <- c(volcano)

measurements <- data.frame(x = runif(30, 1, 80),
                           y = runif(30, 1, 60),
                           thing = rnorm(30))

guide1 <- guide_legend(direction = "horizontal",
                       order = 1)
guide2 <- guide_legend(direction = "horizontal",
                       order = 2)

ggplot(mapping = aes(x, y)) +
  geom_contour(data = topography, aes(z = z, color = stat(level))) +
  scale_color_viridis_c(option = "D", guide = guide1) +
  new_scale_color() +
  geom_point(data = measurements, size = 3, aes(color = thing)) +
  scale_color_viridis_c(option = "A", guide = guide2) +
  theme_bw() +
  theme(legend.position = "top", legend.box = "vertical")
```

![](https://i.imgur.com/F7kGF78.png)

<sup>Created on 2020-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I believe, though, that these questions are better suited for stackoverflow because they are questions about use and options of ggplot2, not bugs or problems present in the ggnewscale package. Furthermore, posting them there allows for greater exposure so that other people with similar problems can find them. I encourage you to [post there](https://stackoverflow.com/questions/tagged/ggplot2).

**Comment by yesdavid** [comment]
Hi @eliocamp, 

thanks for the package! 

I'm having a similiar problem. I added a bunch of `scale_shape_manual` and `ggnewscale::new_scale("shape")` to my plot. Now, the legend is too long/wide to make it fit in a single column/row. 

Is there an option to get the command `guides(scale_shape_manual = guide_legend(ncol = 2))` to work?

Thanks!

Best,
David
