### ISSUE TITLE
Expand to more scales?

### ISSUE THREAD

**Issue by mattansb** [eliocamp/ggnewscale#22]
Are there any plans to expand the pkg to support more scale types? E.g. more than on `linetype` scale, `size`, `shape`, etc...

**Comment by eliocamp** [comment]
Perhaps I didn't explain it enought, but with `new_scale()` you can (in principle) add any scale you want. `new_scale("linetype")`, for example, allows you to have multiple linetype scales. 
Since it's not the main aim of the package, I didn't test it thoroughly, but it should work!

**Comment by mattansb** [comment]
Oh that's great! Thanks!
