### ISSUE TITLE
Possibility to remove individual guides

### ISSUE THREAD

**Issue by Sumidu** [eliocamp/ggnewscale#23]
Hi, 
I love your package. I use the second scale to draw a region based color-coded background. However, the values are not meaningful for the viewer. I would like to hide the guide for only one of the colors. Is this somehow possible?

Thanks so much for this package. :)

**Comment by eliocamp** [comment]
Yes! You can hide any guide by using `guide = "none"` inside the relevant `scale_*()` call.
