### ISSUE TITLE
Legends are not rendered properly except for the last 2 scales

### ISSUE THREAD

**Issue by leesaudan2** [eliocamp/ggnewscale#25]
I have been doing plots with a few colour scales.  It used to be OK up to v0.4.1.  However, after upgrading to v0.4.2, the legend is rendered wrongly.  The colours in the legend are wrong, except for the last 2 scales.

I've constructed a minimal example:
```R
library(ggplot2)
library(ggnewscale)

ggplot(mtcars) + aes(mpg, disp) +
    geom_point(aes(colour=factor(cyl)),  size=7) +
    scale_colour_brewer(type='qual') +
  new_scale_colour() +
    geom_point(aes(colour=factor(carb)), size=5) +
    scale_colour_brewer(type='qual') +
  new_scale_colour() +
    geom_point(aes(colour=factor(gear)), size=3) +
    scale_colour_brewer(palette='Set1') +
  new_scale_colour() +
    geom_point(aes(colour=factor(am)),   size=1) +
    scale_colour_brewer(type='qual')
```
With ggnewscale v0.4.2, this gives:
![Figure 1](https://user-images.githubusercontent.com/25565165/90096468-eb757400-dd65-11ea-9124-ff8f5147e4da.png)

Note that the legend for factor(cyl) and factor(carb) are all black.  They should be coloured!
The expected, correct, behaviour is exhibited by v0.4.1:
![Figure 2](https://user-images.githubusercontent.com/25565165/90096982-75720c80-dd67-11ea-8d6a-ffc65b42e105.png)

**Comment by eliocamp** [comment]
Ahh, damn! This issue is a headache.

This is now "fixed" in the dev branch by reverting #24 fix. Will try to find some workaround and push to CRAN. In the meantime, you can install the dev version with 
```r 
remotes::install_github("eliocamp/ggnewscale@dev") 
```

**Comment by leesaudan2** [comment]
I acknowledge that the new version (dev -> 2e189bd0) works again.  :)
Thanks!

**Comment by eliocamp** [comment]
A true fix (let's hope for real this time) is now on its way to CRAN :)

**Comment by eliocamp** [comment]
Fixed (for real, this time) on master and CRAN. Thanks for reporting the issue!

**Comment by leesaudan2** [comment]
Yes, I can install the newest version (v0.4.3, 55ab803) from CRAN now.
Thanks a lot!  :)
:+1:
