### ISSUE TITLE
help adding specific contour line

### ISSUE THREAD

**Issue by fipoucat** [eliocamp/ggnewscale#28]
Hello Elio,

This is more ask for help than an issue.
I am attempting to plot sea level pressure (isobars) contour on an spatial area with 2mb spacing and want a specific isobar (1015) plotted as thicker line than the others and wonder if it is possible with other function and/or with ggplot2/geom_contour related function or something from ggnewscale. Below the command I used to plot the isobars. Now any idea on how to add a command for the 1015 isobar?

syn_plot <- ggplot() +
geom_tile(data = synclas_gather_df, aes(x=x, y=y, fill=value)) +
geom_sf(data = map_bg, fill="transparent")+
geom_contour2(data = synclas_gather_df, aes(x=x,y=y,z=value), binwidth = 2, color = "black") +
scale_fill_gradientn(colours = colorRamps::matlab.like2(100), name = "hPa",breaks=0:5) +
scale_colour_gradient(guide = 'none') + facet_wrap(~key, ncol = 4) +
scale_x_continuous(limits = c(-34,29), expand = c(0, 0))+
scale_y_continuous(limits = c(-9,34), expand = c(0,0))+
 theme_bw() + theme(axis.title = element_blank(),
 axis.text = element_blank(),
 axis.ticks = element_blank())

  syn_plot + geom_text_contour(data= synclas_gather_df,aes(x,y,z = value), stroke = 0.10,binwidth = 4,size=3)
the data is a data frame  with following format:

  time                              lon    lat      slp
1 1978-12-30 12:00:00   0      40 1015.
 2 1978-12-30 12:00:00   2.5    40 1013.
 3 1978-12-30 12:00:00   5      40 1012.
 4 1978-12-30 12:00:00   7.5    40 1010.
 5 1978-12-30 12:00:00  10      40 1007.
 6 1978-12-30 12:00:00  12.5    40 1005.
 7 1978-12-30 12:00:00  15      40 1004.
 8 1978-12-30 12:00:00  17.5    40 1003.
 9 1978-12-30 12:00:00  20      40 1002.
10 1978-12-30 12:00:00  22.5    40 1001.

Thank you

**Comment by eliocamp** [comment]
Hi!
Just add a second `geom_contour()/geom_contour2()` call with ' breaks = 1015` and increase it's `size`.

**Comment by fipoucat** [comment]
sorry eliocam opening this again.

I am still struggling with my attempt to add a thicker 1015 hPa contour line using below command. Could you help me adjust the code? something looks incorrect.

Thanks
# Plotting the main atmospheric patterns of such a classification
ggplot()+
  geom_raster(filter(cl$grid_clas, var == "mslp"),
              mapping = aes(x,y,fill = mean_WT_value/100),
              interpolate = T,hjust = 0,vjust = 0)+
  geom_sf(data = borders, fill = "transparent")+
  geom_contour2(data = filter(cl$grid_clas,var == "mslp"),
                aes(x,y,z=mean_WT_value/100),
                binwidth = 2, color = "black", size=0.5) +
  geom_text_contour(data= filter(cl$grid_clas, var == "mslp"),
                    aes(x,y,z=mean_WT_value/100),
                    stroke = 0.15,binwidth = 4) +
  guides(fill = guide_colourbar(barwidth = 12, barheight = 0.5))+
  facet_wrap(~WT, ncol = 4) +
  scale_fill_gradientn(colours = pals::jet(100),name = "slp (hPa") +
  scale_x_continuous(limits = c(-35,25), expand = c(0, 0))+
  scale_y_continuous(limits = c(-5,40), expand = c(0,0))+
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    text = element_text(size = 4),
    strip.background = element_rect(fill = "transparent", color = NA),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom")

ggplot()+
  geom_raster(filter(cl$grid_clas, var == "mslp"),
              mapping = aes(x,y,fill = mean_WT_value/100),
              interpolate = T,hjust = 0,vjust = 0)+
  geom_sf(data = borders, fill = "transparent")+
  geom_contour2(data = filter(cl$grid_clas,var == "mslp"),
                aes(x,y,z=mean_WT_value/100),
                breaks=1015 , color = "black", size=1.5) +
  geom_text_contour(data= filter(cl$grid_clas, var == "mslp"),
                    aes(x,y,z=mean_WT_value/100),
                    stroke = 0.15,binwidth = 4) +
  guides(fill = guide_colourbar(barwidth = 12, barheight = 0.5))+
  facet_wrap(~WT, ncol = 4) +
  scale_fill_gradientn(colours = pals::jet(100),name = "slp (hPa") +
  scale_x_continuous(limits = c(-35,25), expand = c(0, 0))+
  scale_y_continuous(limits = c(-5,40), expand = c(0,0))+
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    text = element_text(size = 4),
    strip.background = element_rect(fill = "transparent", color = NA),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom")

**Comment by eliocamp** [comment]
Hi, your code is very complex and I cannot run it because I don't have the data. You can draw a single thick contour line at 1015 hPa with `geom_contour(...., breaks = 1015, linewidth = 1)`, where `...` represents any other arguments such as the data, aesthetics, etc.

**Comment by fipoucat** [comment]
OK, I see no problem.

Thank you again
