### ISSUE TITLE
show.legend = FALSE always applies to all layers 

### ISSUE THREAD

**Issue by ArturLourenco** [eliocamp/ggnewscale#31]
Hola hermano! In this code below, I would like to remove certain legends from some layers using show.legend = FALSE. However, when I desative some legends and let one activated all of them are showed in the final plot.  I'm sending the data reproduce the problem. Maybe because gom_sf? Btw, perfect package to help to build maps using ggplot. Thanks for the job!

```
[data.zip](https://github.com/eliocamp/ggnewscale/files/6436150/data.zip)

load(unzip('data.zip'))

library(ggplot2)
library(ggnewscale)
library(ggspatial)
library(raster)
library(sp)

ggplot() +
  geom_raster(data = basemap_terrain_df_proj, aes(x=x, y=y, fill = as.factor(col)), show.legend = FALSE) + # see here
  scale_fill_manual(values = basemap_colors) +
  new_scale_fill() +
  geom_sf(data = sf_imoveis, aes(fill = NUM_AREA), size = .4, show.legend = TRUE) +
  scale_fill_viridis_c('Área (ha)',option = 'E') +
  new_scale_fill() +
  geom_sf(data = sf_comu, aes(fill = nome, color = nome), fill = NA, size = 1,show.legend = TRUE) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tl") +
  labs(color = "Comunidades",caption = "Fonte dos dados: Mapa Base (Google Maps, 2021).",
       x = "Latitude (m)", y = "Longitude (m)") +
  coord_sf(xlim = c(611500,618000),ylim = c(9140000,9147000),datum = 31984, expand = FALSE, crs = 31984) +
  # guides(color = FALSE, size = FALSE) +
  theme_bw()
```

This is the result:

![image](https://user-images.githubusercontent.com/72623620/117318328-b3b4dc00-ae60-11eb-9558-a4214c31df52.png)

I would like to hide the legend for the geom_raster layer.

**Comment by eliocamp** [comment]
Sorry, I don't understand the issue. Can you post a minimal reproducible example including the output that you get and a description of what you would expect? (Check the [reprex](https://reprex.tidyverse.org/) package for that)

**Comment by ArturLourenco** [comment]
> Sorry, I don't understand the issue. Can you post a minimal reproducible example including the output that you get and a description of what you would expect? (Check the [reprex](https://reprex.tidyverse.org/) package for that)

Yes! I going to update the issue.

**Comment by ArturLourenco** [comment]
Hi. I updated the problem. I think now you can reproduce the behavior. Unfortunately I can't render using reprex, an error is shown.

**Comment by eliocamp** [comment]
If you want to hide the legend for the raster, this should do the trick.

```r
  geom_raster(data = basemap_terrain_df_proj, aes(x=x, y=y, fill = as.factor(col))) +
  scale_fill_manual(values = basemap_colors, guide = "none") 
```
