### ISSUE TITLE
Can't remove guides

### ISSUE THREAD

**Issue by jzadra** [eliocamp/ggnewscale#33]
When using `new_scale_color()`, setting `guides(color = "none")` or `guides(color = F)` only removes the new scale color guide, even if I place one `guides()` line above the `new_scale_color()` and one below.

**Comment by eliocamp** [comment]
You should remove the guide in the scale_color call. Like scale_colour(guide = "none").

**Comment by jzadra** [comment]
Do you mean in the `scale_color_*` family?
