### ISSUE TITLE
guide_legend(ncol=2) 

### ISSUE THREAD

**Issue by yesdavid** [eliocamp/ggnewscale#34]
Hi @eliocamp,
thanks for your package!

I followed this post on SO (https://stackoverflow.com/a/66808609/16642045) and now I'm trying to align the multiple custom legends in two (or more) vertical columns. I tried to add `guides(scale_shape_manual=guide_legend(ncol=2))` to the plot but can't get it to work.

Do you have an idea how to solve this issue?
Thanks!

Best,
David

**Comment by eliocamp** [comment]
I'm closing this since your stackoverflow question is now answered :tada: . Besides, this is a general ggplot2 thing, not something ggnewscale does.

**Comment by eliocamp** [comment]
#57 is now merged.
