### ISSUE TITLE
ggplot2 (3.3.5)

### ISSUE THREAD

**Issue by blakelanglais** [eliocamp/ggnewscale#35]
I'm having some problems with using new_scale() with ggplot2 (v 3.3.5). The last version of ggplot I had working well was 3.3.3. Is anyone else having issues with newer versions of ggplot2?

**Comment by eliocamp** [comment]
Hi, can you post a mnimal reproducible  example to illustrate the problem?

**Comment by blakelanglais** [comment]
I might have jumped the gun posting an issue here. It looks like it's an issue with using multiple layers of the geom_bar() -- not new_scale(). I'll close this. Thanks!
