### ISSUE TITLE
new_scale_*() position matters

### ISSUE THREAD

**Issue by PursuitOfDataScience** [eliocamp/ggnewscale#38]
Hi,

It seems like `new_scale_*()` is doing its job properly after some `scale_*()`. For your README example, if I move `geom_point()` from where it is to where the following example shows, the `new_scale_color()` does not work. Is there a way to solve this problem? For example, if I need to wrap the two `geom_*`s together (in this case, `geom_contour()` and `geom_point()`) as one `geom_combined()` with different color scales, is there a way for me to do that? Thanks. 

```
ggplot(mapping = aes(x, y)) +
  geom_contour(data = topography, aes(z = z, color = stat(level))) +
  geom_point(data = measurements, size = 3, aes(color = thing)) + # moved geom_point to here
  # Color scale for topography
  scale_color_viridis_c(option = "D") +
  # geoms below will use another color scale
  new_scale_color() +
  # Color scale applied to geoms added after new_scale_color()
  scale_color_viridis_c(option = "A")
```

**Comment by eliocamp** [comment]
Yes, `new_scale()` functions create a new scale "slot" that can be used by any geom added after it. The ordering of the calls is what defines which geom uses which scale, so if you add all the geoms first, then there's no way to tell ggplot2 which geoms should use which scale. 

If you want to create your own "geom set" which uses different scales you would do something like this

```r
geom_combined <- function(...) {
list(
geom_contour(data = topography, aes(z = z, color = stat(level))),
 scale_color_viridis_c(option = "D"),
  new_scale_color(),
  geom_point(data = measurements, size = 3, aes(color = thing)),
 scale_color_viridis_c(option = "A")
)
```

If for some reason you really want to define all the geoms together, then you might want to look into [relayer](https://github.com/clauswilke/relayer).
