### ISSUE TITLE
new scale for x/y?

### ISSUE THREAD

**Issue by mattansb** [eliocamp/ggnewscale#42]
Thanks for this great packge!

This would cool if it worked - as it would allow adding a secondary y-axis very easily (compared to the current native method...)

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.1.2

ggplot(mtcars, aes(hp, mpg)) + 
  geom_point(color = "red") + 
  ggnewscale::new_scale("y") + 
  geom_point(aes(y = drat), color = "blue")
#> Scale for 'y_new' is already present. Adding another scale for 'y_new', which
#> will replace the existing scale.
#> Error in `check_required_aesthetics()`:
#> ! new_geom_point requires the following missing aesthetics: y
```

<sup>Created on 2022-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eliocamp** [comment]
Yeah, ggplot2 treats positional scales slightly different. On top of that, the x and y guides are also special; i don't think there's a way adding arbitrary many positional guides. And since ggplot2 already supplies a native method I don't see the use of supporting it in ggnewscale.

**Comment by mattansb** [comment]
Oh well, was worth a shot 🤷‍♂️

(This package is awesome, btw, I use it like a madman...)
