### ISSUE TITLE
Support for plotly

### ISSUE THREAD

**Issue by pmoracho** [eliocamp/ggnewscale#46]
```
ggplot(mapping = aes(x, y)) +
  geom_contour(data = topography, aes(z = z, color = stat(level))) +
  scale_color_viridis_c(option = "D") +
  new_scale_color() +
  geom_point(data = measurements, size = 3, aes(color = thing)) +
  scale_color_viridis_c(option = "A") -> p

  ggplotly(p)

Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_NewGeomContour() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```
![newplot](https://user-images.githubusercontent.com/1447757/162759363-1b0e5636-7139-4c5d-a2c6-da72fba3cf33.png)

The problem seems to be that the classic `geoms` are redefined in `geom_New*` which makes that automatically they cannot be processed by `plotly`, I don't know if there is a way to solve it, but it would be interesting to make this package compatible with `plotly`.

**Comment by eliocamp** [comment]
I have no idea how plotly works, but form what little I've used it, I think it basically hand-crafts translations of each ggplot2 geom to the corresponding plotly mark. If that's the case, then I don't think it'd be possible because the way ggnewscale works is by creating new geoms with new aesthetics for each new scale.

**Comment by eliocamp** [comment]
I've skimmed [the relevant source code](https://github.com/plotly/plotly.R/blob/master/R/layers2traces.R). 

For this specific case you can use:

```r
library(ggplot2)
library(ggnewscale)
# Equivalent to melt(volcano)
topography <- expand.grid(x = 1:nrow(volcano),
                          y = 1:ncol(volcano))
topography$z <- c(volcano)

# point measurements of something at a few locations
set.seed(42)
measurements <- data.frame(x = runif(30, 1, 80),
                           y = runif(30, 1, 60),
                           thing = rnorm(30))

# Defines a the to_basic method to the NewGeomContour class and renames the relevant variables. 
# Very hacky. Don't know how it will generalise. Will break if you add more scales.  
to_basic.NewGeomContour <- function(data, prestats_data, layout, params, p, ...) {
  if (!"fill" %in% names(data)) data$fill <- NA
  colnames(data)[colnames(data) == "colour_new"] <- "colour"
  colnames(data)[colnames(data) == "colour_new_plotlyDomain"] <- "colour_plotlyDomain"

  plotly:::prefix_class(data, "GeomPath")
}


ggplot(mapping = aes(x, y)) +
  geom_contour(data = topography, aes(z = z, color = stat(level))) +
  scale_color_viridis_c(option = "D") +
  new_scale_color() +
  geom_point(data = measurements, size = 3, aes(color = thing)) +
  scale_color_viridis_c(option = "A") -> p

plotly::ggplotly(p)
```

**Comment by pmoracho** [comment]
> I have no idea how plotly works, but form what little I've used it, I think it basically hand-crafts translations of each ggplot2 geom to the corresponding plotly mark. If that's the case, then I don't think it'd be possible because the way ggnewscale works is by creating new geoms with new aesthetics for each new scale.

I understand the same as you do, that's why I assumed that it should not be so easy, but just in case I was asking you.

My concern arose from this: [ggplotly no me grafica el mismo grafico que ggplot](https://es.stackoverflow.com/questions/526532/ggplotly-no-me-grafica-el-mismo-grafico-que-ggplot)

**Comment by pmoracho** [comment]
> ```r
>  if (!"fill" %in% names(data)) data$fill <- NA
>   colnames(data)[colnames(data) == "colour_new"] <- "colour"
>   colnames(data)[colnames(data) == "colour_new_plotlyDomain"] <- "colour_plotlyDomain"
> ```

I tried something very similar, an automatic wrapper of each new geom to the `plotly `function, obviously it solves the warning issue but does not take into account the logic of `ggnewscale`.  

Thanks for your time Elio
