### ISSUE TITLE
error when using geom_raster

### ISSUE THREAD

**Issue by Maschette** [eliocamp/ggnewscale#6]
Hello, 
When I try using new_scale_fill() with geom_raster I get Error: $ operator is invalid for atomic vectors. 

Thanks.

**Comment by Maschette** [comment]
Hi Elio, 
Sorry I should have put one in to begin with. This reproduces the error I get:
```
dat<-raster(nrow=100, ncol=100)
values(dat)<-runif(10000)
data<-as.data.frame(dat, xy=TRUE)
data2<-data[3000:6000,]

ggplot()+geom_raster(data=data, aes(x=x, y=y, fill=layer))+scale_fill_gradientn(colors=c("#959799", "#A0A2A5", "#ACAEB1", "#BDBFC1", "#CED0D1","#E1E2E3", "#F6F7F7"), guide = FALSE)+
  new_scale_fill()+
  geom_raster(data = data2, aes(x=x, y=y), fill="black")+scale_fill_viridis_c()
```

Updating ggplot was the first thing I tried.

**Comment by eliocamp** [comment]
The latest commit should've fixed. It was a problem when a scale had no guide. 
Thanks for reporting the issue! ^_^
