### ISSUE TITLE
Can't have discrete scale before continuous scale

### ISSUE THREAD

**Issue by willgearty** [eliocamp/ggnewscale#8]
Based on the example, I came upon a bug. Converting the color for the points to a discrete scale works, but only as long as it is the second plot.
First do this (after running the earlier code in the example):
```r
measurements <- data.frame(x = runif(30, 1, 80),
                           y = runif(30, 1, 60),
                           thing = sample(1:4, 30, replace = T))
```
Then, if you put the continuous fill first, then add a discrete fill, it works:
```r
ggplot(mapping = aes(x, y)) +
    geom_contour(data = topography, aes(z = z, color = stat(level))) +
    # Color scale for topography
    scale_color_viridis_c(option = "D") +
    # geoms below will use another color scale
    new_scale_color() +
    geom_point(data = measurements, size = 3, aes(color = as.factor(thing)))
```

But if you put the discrete fill first:
```r
ggplot(mapping = aes(x, y)) +
    geom_point(data = measurements, size = 3, aes(color = as.factor(thing))) +
    # Color scale for topography
    scale_color_viridis_c(option = "D") +
    # geoms below will use another color scale
    new_scale_color() +
    geom_contour(data = topography, aes(z = z, color = stat(level)))
```
it gives an error:
```r
Error: Discrete value supplied to continuous scale
```

**Comment by eliocamp** [comment]
I think that's the expected behaviour, isn't it? 
Stat/geoms defined before adding a `new_scale()` use the scales added before the `new_scale()` call. So if you add `geom_contour()` after `new_scale()` you need to add its scale also after `new_scale()`. Like so:

```r
ggplot(mapping = aes(x, y)) +
  # Add geom of measurements
  geom_point(data = measurements, size = 3, aes(color = as.factor(thing))) +
  # Add scale for measurements
  scale_color_discrete() +
  # Add a new scale
  new_scale_color() +
  # Add geom for topography
  geom_contour(data = topography, aes(z = z, color = stat(level))) +
  # Add scale for topography
  scale_color_viridis_c(option = "D") 
```
![image](https://user-images.githubusercontent.com/8617595/60290607-750e7c00-98ef-11e9-8265-809be4ce4dd8.png)

Does this clarify the issue? Is this related to [this](https://github.com/willgearty/deeptime/issues/2) issue? Let me know if there's anything else I can do :)

**Comment by willgearty** [comment]
Whoops, you are totally right, this was just me being silly and forgetting to remove the viridis scale when I swapped the first plot to the discrete color. It came up while I was trying to fix https://github.com/willgearty/deeptime/issues/2, but I don't think it's actually related.
